#!/usr/bin/env node
// Builds the published instruction files from src/. Zero dependencies.
//   node scripts/build.mjs          write the outputs
//   node scripts/build.mjs --check  exit 1 if any output is stale (CI, and before every release)
// Design: app.lunastak.io docs/_plans/2026-09-14-agents-page-design.md
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// Run from anywhere: every path below is relative to the repo root.
process.chdir(resolve(dirname(fileURLToPath(import.meta.url)), '..'))

const check = process.argv.includes('--check')
const fail = (msg) => { console.error(`build: ${msg}`); process.exit(1) }

// The version lives in plugin.json only; marketplace.json must agree.
const plugin = JSON.parse(readFileSync('.claude-plugin/plugin.json', 'utf8'))
const market = JSON.parse(readFileSync('.claude-plugin/marketplace.json', 'utf8'))
const version = plugin.version
if (!/^\d+\.\d+\.\d+$/.test(version)) fail(`plugin.json version "${version}" is not x.y.z`)
const listed = market.plugins.find((p) => p.name === plugin.name)?.version
if (listed !== version) fail(`marketplace.json lists ${plugin.name}@${listed}, plugin.json says ${version}`)

// Each source is LF-only and ends with exactly one newline, so joining with '\n' leaves exactly one
// blank line between them. A CRLF or missing/extra final newline would shift every output silently.
const src = (name) => {
  const text = readFileSync(`src/${name}`, 'utf8')
  if (text.includes('\r')) fail(`src/${name}: contains CR characters — sources must be LF-only`)
  if (!text.endsWith('\n') || text.endsWith('\n\n')) fail(`src/${name}: must end with exactly one newline`)
  return text
}
function fill(text, vars, target) {
  return text.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    if (!(key in vars)) fail(`${target}: unknown placeholder {{${key}}}`)
    return vars[key]
  })
}
// The marker goes LAST in every output: it stays out of the model's opening context, SKILL.md's
// frontmatter stays first, and line 1 of agents.md stays the version H1 (the pointers read it).
const GENERATED = '<!-- GENERATED by scripts/build.mjs from src/ — edit src/, then run `node scripts/build.mjs`. -->'
const withMarker = (text) => text + '\n' + GENERATED + '\n'

// GENERATED_ON is shown as the allowed values, never one concrete value — models copy examples.
// SELF_HELPS / SELF_DOES carry the verb because "this skill" and "these instructions" disagree in number.
const skillVars = {
  VERSION: version,
  GENERATED_BY: `lunastak-skill@${version}`,
  GENERATED_ON: 'claude-code | codex | cursor | claude.ai | other',
  RESUME_HINT: 'use `/lunastak:resume` to continue where you left off — even in a new session',
  SELF_HELPS: 'This skill helps',
  SELF_DOES: 'This Skill Does',
}

const skill = withMarker(
  src('skill-frontmatter.md') + '\n' +
  fill([src('core.md'), src('output-skill.md'), src('tail.md')].join('\n'), skillVars, 'SKILL.md'),
)
// Claude Code only reads the frontmatter if it opens the file and closes before the body.
if (!skill.startsWith('---\n')) fail('SKILL.md: must start with the "---" frontmatter line')
const close = skill.indexOf('\n---\n', 3)
const body = skill.indexOf('\n# ')
if (close === -1 || (body !== -1 && close > body)) fail('SKILL.md: frontmatter does not close before the body')

// agents.md: any agent handed the link (or the pasted text). Chunks only — chat assistants leave
// dimensional tagging to Lunastak. Line 1 must stay the version H1: the platform pointers read it.
const agentsVars = {
  VERSION: version,
  GENERATED_BY: `lunastak-agents@${version}`,
  GENERATED_ON: 'chatgpt | claude.ai | gemini | claude-code | codex | cursor | other',
  // core.md already says "come back with your bundle and …"
  RESUME_HINT: 'bring the link lunastak.io/agents.md to continue where you left off — even in a new conversation',
  SELF_HELPS: 'These instructions help',
  SELF_DOES: 'These Instructions Do',
}
const agents = withMarker(fill(
  [src('agents-header.md'), src('core.md'), src('output-chat.md'), src('agents-checklist.md'), src('tail.md')].join('\n'),
  agentsVars, 'agents.md',
))
if (!agents.startsWith(`# Lunastak agent instructions v${version}\n`)) fail('agents.md: line 1 must be the version H1')

const targets = {
  'skills/decision-stack/SKILL.md': skill,
  'dist/agents.md': agents,
}

const stale = []
for (const [path, content] of Object.entries(targets)) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null
  if (current === content) continue
  if (check) { stale.push(path); continue }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
  console.log(`build: wrote ${path}`)
}
if (check && stale.length) fail(`stale — run node scripts/build.mjs: ${stale.join(', ')}`)
if (check) console.log(`build: all outputs current (v${version})`)
