#!/usr/bin/env node
// Builds the published instruction files from src/. Zero dependencies.
//   node scripts/build.mjs          write the outputs
//   node scripts/build.mjs --check  exit 1 if any output is stale (CI, and before every release)
// Design: app.lunastak.io docs/_plans/2026-09-14-agents-page-design.md
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// Run from anywhere: every path below is relative to the repo root.
process.chdir(resolve(dirname(fileURLToPath(import.meta.url)), '..'))

const check = process.argv.includes('--check')
const fail = (msg) => { console.error(`build: ${msg}`); process.exit(1) }

// The version lives in plugin.json only; marketplace.json must agree.
const plugin = JSON.parse(readFileSync('.claude-plugin/plugin.json', 'utf8'))
const market = JSON.parse(readFileSync('.claude-plugin/marketplace.json', 'utf8'))
const version = plugin.version
if (!/^\d+\.\d+\.\d+$/.test(version)) fail(`plugin.json version "${version}" is not x.y.z`)
const listed = market.plugins.find((p) => p.name === plugin.name)?.version
if (listed !== version) fail(`marketplace.json lists ${plugin.name}@${listed}, plugin.json says ${version}`)

// Each source ends with exactly one newline; joining with '\n' leaves one blank line between them.
const src = (name) => readFileSync(`src/${name}`, 'utf8')
function fill(text, vars, target) {
  return text.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    if (!(key in vars)) fail(`${target}: unknown placeholder {{${key}}}`)
    return vars[key]
  })
}
const GENERATED = '<!-- GENERATED by scripts/build.mjs from src/ — edit src/, then run `node scripts/build.mjs`. -->'

const skillVars = {
  VERSION: version,
  GENERATED_BY: `lunastak-skill@${version}`,
  RESUME_HINT: 'use `/lunastak:resume` to continue where you left off — even in a new session',
}

const targets = {
  // Frontmatter must stay the first thing in SKILL.md, so the marker goes straight after it.
  'skills/decision-stack/SKILL.md':
    src('skill-frontmatter.md') + GENERATED + '\n\n' +
    fill([src('core.md'), src('output-skill.md'), src('tail.md')].join('\n'), skillVars, 'SKILL.md'),
}

const stale = []
for (const [path, content] of Object.entries(targets)) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null
  if (current === content) continue
  if (check) { stale.push(path); continue }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
  console.log(`build: wrote ${path}`)
}
if (check && stale.length) fail(`stale — run node scripts/build.mjs: ${stale.join(', ')}`)
if (check) console.log(`build: all outputs current (v${version})`)
